import {lazy,Suspense,useEffect,useMemo,useRef,useState} from 'react';
import {Plus,Database,ArrowUpRight,Check,Download,Trash2} from 'lucide-react';
import {compileRecipe,validateRecipe,TEMPLATE_NAMES} from '@maker/product-recipes';
import {formatMoney} from '@arc/configurator/product';
import {api,exportJSON} from './api.js';
import {Field,NumberField,Select,Modal,MaterialFields} from './Fields.jsx';
import './studio.css';
const ScenePreview=lazy(()=>import('./ScenePreview.jsx'));
const tabs=['Overview','Dimensions','Materials','Pricing','Sources'];
const confidence=['published','photo-derived','estimated','workspace'];
const deep=structuredClone;
const labelFor={height:'Height',topThickness:'Top thickness',edgeDepth:'Apparent edge depth',legWidth:'Leg width',baseDiameter:'Base diameter',columnDiameter:'Column diameter',baseThickness:'Base thickness'};
const storefront=(r,v)=>'/products/'+r.id+'?version='+v;
export default function ProductStudio(){
  const [list,setList]=useState([]),[id,setId]=useState(()=>new URLSearchParams(location.search).get('product')||'vft-bistro-round'),[entries,setEntries]=useState({}),[tab,setTab]=useState('Dimensions'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState(''),[library,setLibrary]=useState(null);
  const [sizeId,setSizeId]=useState('36'),[topId,setTopId]=useState(''),[baseId,setBaseId]=useState(''),[materialGroup,setMaterialGroup]=useState('finishes'),[materialId,setMaterialId]=useState('');
  const [cloneTitle,setCloneTitle]=useState(''),[cloneId,setCloneId]=useState(''),[presetId,setPresetId]=useState(''),[rule,setRule]=useState({finish:'',baseFinish:'',reason:''});
  const [priceSize,setPriceSize]=useState(''),[newSize,setNewSize]=useState(42);
  const entry=entries[id],recipe=entry?.draft,dirty=!!entry&&JSON.stringify(entry.draft)!==JSON.stringify(entry.saved);
  const dirtyAny=Object.values(entries).some(e=>JSON.stringify(e.draft)!==JSON.stringify(e.saved));
  const lastScene=useRef(null);
  async function refreshList(){setList(await api('studio/recipes'));}
  useEffect(()=>{const abort=new AbortController();Promise.all([api('studio/recipes',undefined,'GET',abort.signal),api('studio/materials',undefined,'GET',abort.signal)]).then(([l,m])=>{setList(l);setLibrary(m);setPresetId(m.presets[0]?.id||'');}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[]);
  useEffect(()=>{if(entries[id])return;const abort=new AbortController();api('studio/recipes/'+id,undefined,'GET',abort.signal).then(record=>setEntries(e=>({...e,[id]:{...record,saved:deep(record.draft)}}))).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[id,entries]);
  useEffect(()=>{const handler=e=>{if(dirtyAny){e.preventDefault();e.returnValue='';}};addEventListener('beforeunload',handler);return()=>removeEventListener('beforeunload',handler);},[dirtyAny]);
  function edit(fn){if(busy)return;setEntries(all=>{const current=all[id];if(!current)return all;const draft=deep(current.draft);fn(draft);return {...all,[id]:{...current,draft}};});setNotice('');}
  const preview=useMemo(()=>{if(!recipe)return {issues:[]};const issues=validateRecipe(recipe);if(issues.length)return {issues};try{const product=compileRecipe(recipe);const size=recipe.sizes.find(s=>s.id===sizeId)||recipe.sizes.find(s=>s.id===recipe.defaults.size);const config={...product.defaults,size:size.id,finish:recipe.finishes.some(f=>f.id===topId)?topId:recipe.defaults.finish,baseFinish:recipe.baseFinishes.some(f=>f.id===baseId)?baseId:recipe.defaults.baseFinish};const result=product.evaluate(config);return {issues:[],scene:product.scene(config),result};}catch(e){return {issues:e.issues||[{message:e.message}]};}},[recipe,sizeId,topId,baseId]);
  useEffect(()=>{if(preview.scene)lastScene.current=preview.scene;},[preview.scene]);
  async function run(action){if(busy)return;setBusy(true);setError('');try{await action();}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function save(){const result=await api('studio/recipes/'+id,{recipe,revision:entry.revision},'PUT');setEntries(e=>({...e,[id]:{...result,saved:deep(result.draft)}}));await refreshList();return result;}
  async function publish(){let current=entry;if(dirty)current=await save();const result=await api('studio/recipes/'+id+'/publish',{revision:current.revision});setEntries(e=>({...e,[id]:{...result,saved:deep(result.draft)}}));await refreshList();setNotice('Version '+result.versions.at(-1).version+' published locally. Earlier versions are unchanged.');}
  function switchProduct(next){const url=new URL(location.href);url.searchParams.set('product',next);history.replaceState(null,'',url);setId(next);setSizeId('');setTopId('');setBaseId('');setMaterialId('');setPriceSize('');setError('');setNotice('');}
  async function cloneRecipe(){if(dirty)await save();const result=await api('studio/recipes/'+id+'/clone',{id:cloneId,title:cloneTitle});setEntries(e=>({...e,[cloneId]:{...result,saved:deep(result.draft)}}));await refreshList();setModal('');switchProduct(cloneId);setNotice('Cloned as an unpublished, quote-only draft.');}
  function setGeometry(key,value){edit(r=>{r.geometry[key]={value,confidence:'workspace'};if(key==='topThickness'&&r.geometry.edgeDepth.value<value)r.geometry.edgeDepth={value,confidence:'workspace'};});}
  const selectedSize=recipe?.sizes.find(s=>s.id===sizeId)||recipe?.sizes.find(s=>s.id===recipe.defaults.size);
  const selectedMaterial=recipe?.[materialGroup]?.find(f=>f.id===materialId)||recipe?.[materialGroup]?.find(f=>f.id===recipe.defaults[materialGroup==='finishes'?'finish':'baseFinish'])||recipe?.[materialGroup]?.[0];
  const selectedPreset=library?.presets.find(p=>p.id===presetId)||library?.presets[0];
  const latest=entry?.versions.at(-1);
  const price=preview.result?.quote;const priceLabel=price?.status==='reference'?formatMoney(price.totalMinor,price.currency)+' '+price.currency:'Quote required';
  const canSave=recipe&&!preview.issues.length&&!busy;
  const updateMaterial=material=>{edit(r=>{const index=r[materialGroup].findIndex(f=>f.id===selectedMaterial.id);r[materialGroup][index]={...material,id:selectedMaterial.id};});if(materialGroup==='finishes')setTopId(selectedMaterial.id);else setBaseId(selectedMaterial.id);};
  function applyPreset(){if(!selectedPreset||!selectedMaterial)return;updateMaterial({...deep(selectedPreset),id:selectedMaterial.id});setModal('');setNotice('Preset copied into this draft. Published versions keep their own material settings.');}
  function addSize(){edit(r=>{const newId='size-'+newSize.toString().replace('.','-');if(r.sizes.some(s=>s.id===newId))return;r.sizes.push({id:newId,length:newSize,width:r.template==='pedestal'?newSize:selectedSize.width,confidence:'workspace'});setSizeId(newId);});}
  return <div className="product-studio">
    <header className="ps-header"><a className="ps-brand" href="/studio">Maker Studio</a><span className="ps-header-section">Product recipes</span><div className="ps-header-actions"><a className="ps-button ps-outline" href="/manage">Management</a>{latest&&<a className="ps-button ps-outline" href={storefront(recipe,latest.version)} target="_blank" rel="noreferrer">Preview storefront <ArrowUpRight size={15}/></a>}<button className="ps-button ps-primary" disabled={!canSave} onClick={()=>run(publish)}>Publish version <ArrowUpRight size={15}/></button></div></header>
    <aside className="ps-sidebar"><div className="ps-sidebar-heading">Products <span>{list.length.toString().padStart(2,'0')}</span></div><button className="ps-clone" disabled={!recipe||busy} onClick={()=>{setCloneTitle(recipe.title+' — studio edition');setCloneId(recipe.id+'-copy');setModal('clone');}}><Plus size={16}/> Clone recipe</button><nav aria-label="Product recipes">{list.map(p=><button key={p.id} disabled={busy} onClick={()=>switchProduct(p.id)} className={id===p.id?'selected':''} aria-current={id===p.id?'page':undefined}><strong>{entries[p.id]?.draft.title||p.title}</strong><span>{entries[p.id]?.draft.maker||p.maker}</span>{entries[p.id]&&JSON.stringify(entries[p.id].draft)!==JSON.stringify(entries[p.id].saved)&&<i aria-label="Unsaved draft"/>}</button>)}</nav><div className="ps-sidebar-bottom"><button onClick={()=>setModal('library')} disabled={!library}><Database size={17}/> Material library</button><a href="/">Original Parsons demo <ArrowUpRight size={13}/></a></div></aside>
    <main className="ps-workspace">
      {!recipe?<div className="ps-loading">{error||'Opening your workspace…'}</div>:<><div className="ps-identity"><div><p className="ps-eyebrow">PRODUCT RECIPE / {recipe.template==='pedestal'?'02':'01'}</p><h1>{recipe.title}</h1><p className="ps-maker">{recipe.maker}</p></div><span className="ps-draft"><i/> Draft · Local workspace</span></div>
      <div className="ps-tabs" role="tablist" aria-label="Recipe sections">{tabs.map(t=><button role="tab" aria-selected={tab===t} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>
      <div className="ps-split"><section className="ps-properties" aria-label={tab+' recipe settings'} inert={busy}>
        {tab==='Overview'&&<><h2>Product identity</h2><Field label="Product name"><input value={recipe.title} maxLength={100} onChange={e=>edit(r=>{r.title=e.target.value;})}/></Field><Field label="Maker"><input value={recipe.maker} maxLength={100} onChange={e=>edit(r=>{r.maker=e.target.value;})}/></Field><p className="ps-help">Product ID: <code>{recipe.id}</code><br/>Independent demonstration. No maker approval implied.</p><h3>Starting configuration</h3><Select label="Default size" value={recipe.defaults.size} onChange={value=>edit(r=>{r.defaults.size=value;})} options={recipe.sizes.map(s=>({id:s.id,name:s.length+' in'}))}/><Select label="Default top" value={recipe.defaults.finish} onChange={value=>edit(r=>{r.defaults.finish=value;})} options={recipe.finishes}/>{recipe.template==='pedestal'&&<Select label="Default base" value={recipe.defaults.baseFinish} onChange={value=>edit(r=>{r.defaults.baseFinish=value;})} options={recipe.baseFinishes}/>}<h3>Studio camera</h3><div className="ps-two"><NumberField label="Yaw" value={recipe.camera.yaw} onChange={v=>edit(r=>{r.camera.yaw=v;})} min={-180} max={180} step={1} unit="°"/><NumberField label="Elevation" value={recipe.camera.elevation} onChange={v=>edit(r=>{r.camera.elevation=v;})} min={15} max={75} step={1} unit="°"/></div><NumberField label="Camera distance" value={recipe.camera.distance} onChange={v=>edit(r=>{r.camera.distance=v;})} min={.8} max={1.8} step={.05} unit="×"/><h3>Published versions</h3>{entry.versions.length?entry.versions.slice().reverse().map(v=><a className="ps-version" key={v.version} target="_blank" rel="noreferrer" href={storefront(recipe,v.version)}>Version {v.version}<span>{new Date(v.publishedAt).toLocaleDateString()} <ArrowUpRight size={13}/></span></a>):<p className="ps-help">This draft has not been published.</p>}<button className="ps-text-button" onClick={()=>exportJSON(recipe,recipe.id+'-recipe.json')}><Download size={14}/> Export recipe JSON</button></>}
        {tab==='Dimensions'&&<><h2>Size &amp; geometry</h2><Field label="Shape"><div className="ps-static">{TEMPLATE_NAMES[recipe.template]}</div></Field><Field label="Standard sizes"><span className="ps-size-buttons">{recipe.sizes.map(s=><button key={s.id} className={selectedSize.id===s.id?'selected':''} aria-pressed={selectedSize.id===s.id} onClick={()=>setSizeId(s.id)}>{s.length} in</button>)}</span></Field><div className="ps-two"><NumberField label={recipe.template==='pedestal'?'Diameter':'Length'} value={selectedSize.length} onChange={v=>edit(r=>{const s=r.sizes.find(s=>s.id===selectedSize.id);s.length=v;if(r.template==='pedestal')s.width=v;s.confidence='workspace';})}/><NumberField label="Height" value={recipe.geometry.height.value} onChange={v=>setGeometry('height',v)}/></div>{recipe.template==='parsons'&&<NumberField label="Width" value={selectedSize.width} onChange={v=>edit(r=>{const s=r.sizes.find(s=>s.id===selectedSize.id);s.width=v;s.confidence='workspace';})}/>}<p className="ps-help">{recipe.geometry.height.confidence==='published'?'Height from published product data.':'Height is an estimate — maker measurement needed.'}</p><h3>Construction</h3>{(recipe.template==='pedestal'?['topThickness','baseDiameter','columnDiameter']:['topThickness','edgeDepth','legWidth']).map(k=><NumberField key={k} label={labelFor[k]} value={recipe.geometry[k].value} onChange={v=>setGeometry(k,v)}/>)}<p className="ps-evidence"><span/> Photo-derived geometry</p><details><summary>Size catalog &amp; preview limits</summary><div className="ps-two"><NumberField label="New standard size" value={newSize} onChange={setNewSize}/><button className="ps-button" onClick={addSize} disabled={!newSize||recipe.sizes.length>=20}>Add size</button></div>{recipe.sizes.length>1&&selectedSize.id!==recipe.defaults.size&&<button className="ps-text-button" onClick={()=>{edit(r=>{r.sizes=r.sizes.filter(s=>s.id!==selectedSize.id);r.pricing.variants=r.pricing.variants.filter(v=>v.size!==selectedSize.id);});setSizeId(recipe.defaults.size);}}>Remove selected size and its price rows</button>}{(recipe.template==='pedestal'?['length','height']:['length','width','height']).map(k=><div key={k}><h4>{k==='length'&&recipe.template==='pedestal'?'Diameter':k}</h4><div className="ps-two">{['min','max'].map(bound=><NumberField key={bound} label={k+' '+bound} value={recipe.limits[k][bound]} onChange={v=>edit(r=>{r.limits[k][bound]=v;if(r.template==='pedestal'&&k==='length')r.limits.width[bound]=v;})}/>)}</div></div>)}<p className="ps-help">Custom limits define preview ranges, not manufacturing approval. Dimensions changed here require a new quote.</p></details><p className="ps-form-foot">Changes update the preview.</p></>}
        {tab==='Materials'&&<><h2>Surface &amp; finish</h2><div className="ps-segments">{['finishes',...(recipe.template==='pedestal'?['baseFinishes']:[])].map(g=><button key={g} aria-pressed={materialGroup===g} className={materialGroup===g?'selected':''} onClick={()=>{setMaterialGroup(g);setMaterialId('');}}>{g==='finishes'?'Hardwood top':'Steel base'}</button>)}</div><Select label="Finish option" value={selectedMaterial.id} onChange={value=>{setMaterialId(value);if(materialGroup==='finishes')setTopId(value);else setBaseId(value);}} options={recipe[materialGroup]}/><MaterialFields material={selectedMaterial} onChange={updateMaterial}/><button className="ps-text-button" onClick={()=>setModal('library')}><Database size={15}/> Apply a material preset</button><button className="ps-text-button" disabled={recipe[materialGroup].length>=32} onClick={()=>{setCloneTitle(selectedMaterial.name+' variation');setCloneId(selectedMaterial.id+'-copy');setModal('finish');}}><Plus size={14}/> Add finish option</button><details><summary>Compatibility rules</summary><p className="ps-help">Exclude a top and base combination with a reason. The default combination must remain valid.</p><Select label="Rule top" value={rule.finish||recipe.finishes[0].id} onChange={v=>setRule(p=>({...p,finish:v}))} options={recipe.finishes}/><Select label="Rule base" value={rule.baseFinish||recipe.baseFinishes[0].id} onChange={v=>setRule(p=>({...p,baseFinish:v}))} options={recipe.baseFinishes}/><Field label="Reason"><input value={rule.reason} onChange={e=>setRule(p=>({...p,reason:e.target.value}))}/></Field><button className="ps-button" disabled={!rule.reason.trim()} onClick={()=>{edit(r=>{r.rules.push({finish:rule.finish||recipe.finishes[0].id,baseFinish:rule.baseFinish||recipe.baseFinishes[0].id,reason:rule.reason});});setRule(p=>({...p,reason:''}));}}>Add exclusion</button>{recipe.rules.map((r,i)=><div className="ps-rule" key={i}><span>{r.finish} + {r.baseFinish}<small>{r.reason}</small></span><button className="ps-icon" aria-label={'Remove rule '+(i+1)} onClick={()=>edit(r=>{r.rules.splice(i,1);})}><Trash2 size={15}/></button></div>)}</details></>}
        {tab==='Pricing'&&<><h2>Reference pricing</h2><Select label="Pricing behavior" value={recipe.pricing.mode} onChange={mode=>edit(r=>{r.pricing.mode=mode;})} options={[{id:'quote',name:'Maker quote required'},{id:'reference',name:'Reference price when available'}]}/><Select label="Currency" value={recipe.currency} onChange={value=>edit(r=>{r.currency=value;r.pricing.provenance='workspace';r.pricing.mode='quote';r.pricing.variants.forEach(v=>{v.amountMinor=null;});})} options={['USD','CAD','EUR','GBP']}/><p className="ps-help">{recipe.pricing.variants.length} catalog combinations. Unknown prices stay blank. Changing currency clears reference amounts; it does not convert them.</p><p className="ps-evidence">Custom or altered dimensions always require a quote.</p><Select label="Price rows for size" value={priceSize||recipe.sizes[0].id} onChange={setPriceSize} options={recipe.sizes.map(s=>({id:s.id,name:s.length+' in'}))}/><div className="ps-prices">{recipe.pricing.variants.filter(v=>v.size===(priceSize||recipe.sizes[0].id)).map(v=><Field key={[v.size,v.finish,v.baseFinish].join('|')} label={(recipe.finishes.find(f=>f.id===v.finish)?.name||v.finish)+(recipe.template==='pedestal'?' · '+recipe.baseFinishes.find(f=>f.id===v.baseFinish)?.name:'')}><input aria-label={'Price '+v.finish+' '+v.baseFinish} type="number" min="0.01" step="0.01" placeholder="Quote required" value={v.amountMinor===null?'':v.amountMinor/100} onChange={e=>{const amount=e.target.value;edit(r=>{const row=r.pricing.variants.find(x=>x.id===v.id);row.amountMinor=amount===''?null:Math.round(Number(amount)*100);r.pricing.provenance='workspace';});}}/></Field>)}</div><p className="ps-help">Amounts entered here are workspace references. Taxes and shipping are excluded. These are not offers from the maker.</p></>}
        {tab==='Sources'&&<><h2>Evidence &amp; accuracy</h2>{recipe.sources.map((s,i)=><div className="ps-source" key={i}><Field label={'Source '+(i+1)}><input value={s.label} onChange={e=>edit(r=>{r.sources[i].label=e.target.value;})}/></Field><Field label="Public URL"><input type="url" value={s.url} onChange={e=>edit(r=>{r.sources[i].url=e.target.value;})}/></Field><Field label="Observed"><input type="date" value={s.observed} onChange={e=>edit(r=>{r.sources[i].observed=e.target.value;})}/></Field><a href={/^https?:\/\//.test(s.url)?s.url:undefined} target="_blank" rel="noreferrer">Open source <ArrowUpRight size={12}/></a>{recipe.sources.length>1&&<button className="ps-text-button" onClick={()=>edit(r=>{r.sources.splice(i,1);})}>Remove source</button>}</div>)}<button className="ps-text-button" onClick={()=>edit(r=>{r.sources.push({label:'New source',url:'',observed:new Date().toISOString().slice(0,10)});})}><Plus size={14}/> Add source</button><h3>Measurement confidence</h3>{Object.entries(recipe.geometry).filter(([k])=>recipe.template==='pedestal'?!['legWidth','edgeDepth'].includes(k):!['baseDiameter','columnDiameter','baseThickness'].includes(k)).map(([k,g])=><Select key={k} label={labelFor[k]} value={g.confidence} onChange={v=>edit(r=>{r.geometry[k].confidence=v;})} options={confidence}/>)}<Field label="Accuracy note"><textarea rows={7} value={recipe.notes} maxLength={4000} onChange={e=>edit(r=>{r.notes=e.target.value;})}/></Field></>}
      </section><Suspense fallback={<div className="ps-scene ps-loading">Preparing the studio…</div>}><ScenePreview scene={preview.scene||lastScene.current} title={recipe.title} price={priceLabel}/></Suspense></div>
      {preview.issues.length>0&&<div className="ps-validation" role="alert"><strong>Fix before saving · preview shows the last valid configuration.</strong>{preview.issues.slice(0,4).map((issue,i)=><p key={i}>{issue.field}: {issue.message}</p>)}</div>}
      </>}
    </main>
    <footer className="ps-status"><span aria-live="polite">{error?<span className="ps-status-error">{error} <button onClick={()=>run(async()=>{const r=await api('studio/recipes/'+id);setEntries(e=>({...e,[id]:{...r,saved:deep(r.draft)}}));setNotice('Saved draft reloaded.');})}>Reload saved draft</button></span>:notice||<><Check size={13}/>{dirty?'Unsaved changes':'Saved locally'}</>}</span><div>{dirty&&<button disabled={!canSave} onClick={()=>run(async()=>{await save();setNotice('Draft saved locally.');})}>{busy?'Saving…':'Save draft'}</button>}<span>Recipe {latest?.version||'draft'} · No live orders</span></div></footer>
    {modal==='finish'&&<Modal title="Add a finish option" onClose={()=>setModal('')}><p className="ps-help">Copies the selected finish as a new choice. Combinations with this option require a quote.</p><Field label="Finish label"><input value={cloneTitle} onChange={e=>setCloneTitle(e.target.value)}/></Field><Field label="Finish ID"><input value={cloneId} onChange={e=>setCloneId(e.target.value)}/></Field><button className="ps-button ps-primary" disabled={!/^[a-z][a-z0-9-]{1,63}$/.test(cloneId)||!cloneTitle.trim()||recipe[materialGroup].some(m=>m.id===cloneId)} onClick={()=>{edit(r=>{r[materialGroup].push({...deep(selectedMaterial),id:cloneId,name:cloneTitle});});setMaterialId(cloneId);if(materialGroup==='finishes')setTopId(cloneId);else setBaseId(cloneId);setModal('');}}>Add option</button></Modal>}
    {modal==='clone'&&<Modal title="Clone this recipe" onClose={()=>setModal('')}><p className="ps-help">Start a new product using the same geometry template. The copy starts with quote-only pricing.</p><Field label="New product name"><input value={cloneTitle} onChange={e=>setCloneTitle(e.target.value)}/></Field><Field label="New product ID" note="Lowercase letters, numbers and hyphens."><input value={cloneId} onChange={e=>setCloneId(e.target.value)}/></Field><button className="ps-button ps-primary" disabled={busy||!cloneTitle||!cloneId||preview.issues.length>0} onClick={()=>run(cloneRecipe)}>Create draft</button>{error&&<p role="alert" className="ps-modal-error">{error}</p>}</Modal>}
    {modal==='library'&&library&&<Modal title="Material library" onClose={()=>setModal('')}><p className="ps-help">Reusable visual presets. Applying one copies its settings into the selected recipe finish.</p><Select label="Library preset" value={selectedPreset.id} onChange={setPresetId} options={library.presets}/><MaterialFields material={selectedPreset} onChange={p=>setLibrary(l=>({...l,presets:l.presets.map(m=>m.id===p.id?p:m)}))}/><div className="ps-modal-actions"><button className="ps-button" disabled={busy} onClick={()=>run(async()=>{setLibrary(await api('studio/materials',library,'PUT'));setNotice('Material library saved locally.');})}>Save library</button><button className="ps-button ps-primary" disabled={!selectedMaterial||busy} onClick={applyPreset}>Apply to {materialGroup==='finishes'?'top':'base'}</button></div>{error&&<p role="alert" className="ps-modal-error">{error}</p>}</Modal>}
  </div>;
}

