import {catalog,compatibility,categories,sidewalls,layups,flexOptions,PRICES} from '@arc/brand-on3p';
import {bindingCatalog} from '@arc/brand-on3p';
import {compileRecipe} from '@maker/product-recipes';
const choices=list=>list.map(v=>typeof v==='object'?{value:v.id,label:v.name||v.id}:{value:v,label:String(v)});
export async function managementCatalog(recipes,products){
  const published=await recipes.catalog(),lists=await recipes.list();
  const ski=products.get('on3p-custom-ski');
  const skiOptions={category:choices(categories),model:catalog.models.map(m=>({value:m.handle,label:m.name})),length:[...new Set(catalog.models.flatMap(m=>m.lengths.map(l=>l.length_cm)))].sort((a,b)=>a-b).map(n=>({value:n,label:n+' cm'})),rocker:choices(['Signature','Ripper']),layup:choices(layups),flex:choices(flexOptions),sidewall:sidewalls.map(([name])=>({value:name,label:name})),top:choices(catalog.tops),base:choices(catalog.bases),detune:choices([true,false]),skinClip:choices([true,false]),binding:[{value:'',label:'Skis only'},...bindingCatalog.products.flatMap(p=>p.variants.map(v=>({value:v.id,label:p.name+' / '+v.color+' / '+v.brake+' mm'})))]};
  const result=[{id:ski.id,title:ski.title,version:ski.version,currency:'USD',editor:null,fields:Object.entries(ski.defaults).map(([id,value])=>({id,type:id==='length'?'number':typeof value,choices:skiOptions[id]||[]})),referenceRows:[{label:'Custom ski pair',amountMinor:PRICES.skis*100},{label:'Park detune (where offered)',amountMinor:PRICES.detune*100},{label:'Skin clip (when not included)',amountMinor:PRICES.skinClip*100},...bindingCatalog.products.flatMap(p=>p.variants.map(v=>({label:p.name+' / '+v.color+' / '+v.brake+' mm'+(v.available?'':' — unavailable'),amountMinor:Math.round(v.price*100)}))),...layups.map(l=>({label:l.id+' layup',amountMinor:l.price*100})),...sidewalls.map(([name])=>({label:name+' sidewalls',amountMinor:name==='Black'?0:PRICES.sidewall*100})),...flexOptions.map(f=>({label:f.id+' flex',amountMinor:f.id==='Stock'?0:PRICES.flex*100})),...catalog.tops.map(t=>({label:t.name+' topsheet',amountMinor:(compatibility.prices.tops[t.id]||0)*100})),...catalog.bases.map(b=>({label:b.name+' base',amountMinor:(compatibility.prices.bases[b.id]||0)*100}))],source:compatibility.source,observed:compatibility.observed}];
  for(const info of lists){const r=published.find(r=>r.id===info.id)||(await recipes.get(info.id)).draft,product=compileRecipe(r);const options={size:r.sizes.map(s=>({value:s.id,label:s.length+' in'})).concat({value:'custom',label:'Custom'}),finish:choices(r.finishes),baseFinish:choices(r.baseFinishes)};result.push({id:r.id,title:r.title,version:info.latestVersion||'draft',currency:r.currency,editor:'/studio?product='+r.id,fields:Object.entries(product.defaults).map(([id,value])=>({id,type:typeof value,choices:options[id]||[]})),referenceRows:r.pricing.variants.map(v=>({label:[v.size,r.finishes.find(f=>f.id===v.finish)?.name,r.baseFinishes.find(f=>f.id===v.baseFinish)?.name].filter(Boolean).join(' / '),amountMinor:v.amountMinor})),source:r.sources[0]?.url,observed:r.sources[0]?.observed});}
  return result;
}
