// Stock collection snapshot (September 2026). Live prices and availability are confirmed at Praxis.
// Copy is paraphrased from each Praxis product page; photos are Praxis originals, in gallery order.
// `custom` names the matching custom-order model, when Praxis offers one.
export const products = [
  {
    id: 'gpo',
    name: 'GPO',
    price: 900,
    source: 'https://www.praxisskis.com/skis/gpo/',
    photos: ['gpo-2.jpg', 'gpo-0.jpg', 'gpo-1.jpg', 'gpo-3.jpg'],
    lengths: [155, 165, 175, 182, 187, 192],
    terrain: ['All mountain', 'Powder'],
    veneer: 'Red gum',
    core: 'Maple, ash & aspen',
    flex: 'Length dependent',
    profile: 'Tapered, rockered tip and tail',
    tagline: 'Freeride, with a playful side.',
    description: 'A versatile freeride shape that moves easily between carving, slarving and open-mountain turns. The tapered tip and tail bring a loose, playful feel to serious terrain.',
    custom: 'gpo',
  },
  {
    id: 'exp',
    name: 'EXP',
    price: 1000,
    source: 'https://www.praxisskis.com/skis/exp/',
    photos: ['exp-1.jpg', 'exp-0.jpg', 'exp-2.jpg'],
    lengths: [173, 183],
    terrain: ['Touring'],
    veneer: 'Ambrosia maple',
    core: 'Ultralight',
    flex: '3',
    profile: 'Subtle tip rocker, flatter tapered tail',
    waist: 88,
    tagline: 'Go further. Travel lighter.',
    description: 'A lightweight expedition ski with an 88 mm waist and a generous, tapered tip. Built for easy turns and efficient travel through remote, variable terrain.',
    custom: 'exp',
  },
  {
    id: 'snd',
    name: 'SND',
    price: 850,
    source: 'https://www.praxisskis.com/skis/snd/',
    photos: ['snd-0.jpg', 'snd-1.jpg', 'snd-2.jpg', 'snd-3.jpg'],
    lengths: [167, 176, 185],
    terrain: ['Carving'],
    veneer: 'Poplar',
    core: 'Maple & ash',
    flex: '5',
    profile: 'Progressive sidecut',
    tagline: 'Every turn, an occasion.',
    description: 'The Slice-N-Dice brings a GS-inspired shape and responsive, progressive sidecut to the frontside. Drive into the tip and let the turn tighten beneath you.',
    custom: 'snd',
  },
  {
    id: 'mvp-94',
    name: 'MVP 94',
    price: 850,
    source: 'https://www.praxisskis.com/skis/mvp-94/',
    photos: ['mvp-94-2.jpg', 'mvp-94-0.jpg', 'mvp-94-1.jpg', 'mvp-94-3.jpg'],
    lengths: [154, 164, 174, 184],
    terrain: ['All mountain', 'Carving'],
    veneer: 'Red gum',
    core: 'Maple & ash',
    flex: 'Length dependent',
    profile: 'Tapered directional shape',
    waist: 94,
    tagline: 'A daily driver with an edge.',
    description: 'A narrower take on the MVP platform with a 94 mm waist and a supportive maple-and-ash core. Built for quick transitions and confident everyday turns.',
    custom: 'mvp-94',
  },
  {
    id: '9d8',
    name: '9D8',
    price: 850,
    source: 'https://www.praxisskis.com/skis/9d8/',
    photos: ['9d8-2.jpg', '9d8-0.jpg', '9d8-1.jpg'],
    lengths: [173, 179, 185, 191],
    terrain: ['All mountain'],
    veneer: 'Cherry',
    core: 'Maple & ash',
    flex: '4',
    profile: 'Subtle tip rocker',
    waist: 98,
    tagline: 'Make the whole mountain yours.',
    description: 'A 98 mm waist, a powerful core and a subtle tip rocker make the 9D8 an adaptable option for changing conditions around the resort.',
    custom: '9d8',
  },
  {
    id: 'praxis-slugger',
    name: 'Slugger',
    price: 850,
    source: 'https://www.praxisskis.com/skis/praxis-slugger/',
    photos: ['praxis-slugger-2.jpg', 'praxis-slugger-0.jpg', 'praxis-slugger-1.jpg', 'praxis-slugger-3.jpg'],
    lengths: [165, 175, 185],
    terrain: ['All mountain'],
    veneer: 'Cherry',
    core: 'Maple & ash',
    flex: '4',
    profile: 'Directional all-mountain shape',
    waist: 102,
    tagline: 'Power through the everyday.',
    description: 'A 102 mm platform with a solid maple-and-ash core. The Slugger pairs a substantial tip with a more tapered tail for strong, directional turns.',
    custom: 'slugger',
  },
  {
    id: 'bc',
    name: 'BC',
    price: 900,
    priceFrom: true,
    source: 'https://www.praxisskis.com/skis/bc/',
    photos: ['bc-1.jpg', 'bc-0.jpg', 'bc-2.jpg', 'bc-3.jpg'],
    lengths: [150, 160, 170, 180, 185, 190],
    terrain: ['Touring', 'All mountain'],
    veneer: 'Cherry',
    core: 'Ultralight with carbon',
    flex: 'Length dependent',
    profile: 'Low camber with tip rocker',
    tagline: 'Earn your turns. Enjoy the descent.',
    description: 'The BC balances uphill efficiency with an easygoing descent. A light core, carbon reinforcement and a versatile shape keep long days in the backcountry in focus.',
    custom: 'bc',
  },
  {
    id: 'frd',
    name: 'FRD',
    price: 900,
    source: 'https://www.praxisskis.com/skis/frd/',
    photos: ['frd-0.jpg', 'frd-1.jpg', 'frd-2.jpg', 'frd-3.jpg'],
    lengths: [164, 174, 184, 194],
    terrain: ['All mountain', 'Powder'],
    veneer: 'Cherry',
    core: 'Maple & ash with carbon',
    flex: '4',
    profile: 'Camber, gradual tip rise, flat tail',
    tagline: 'For the line you have in mind.',
    description: 'A directional freeride ski with traditional camber and a supportive, flatter tail. Made for skiers who prefer to drive the turn and finish it with authority.',
    custom: 'frd',
  },
  {
    id: 'mvp-108',
    name: 'MVP 108',
    price: 900,
    source: 'https://www.praxisskis.com/skis/mvp-108/',
    photos: ['mvp-108-1.jpg', 'mvp-108-0.jpg', 'mvp-108-2.jpg'],
    lengths: [163, 173, 183, 188, 193],
    terrain: ['All mountain', 'Powder'],
    veneer: 'Birch',
    core: 'Maple, ash & aspen',
    flex: '4',
    profile: 'Tapered freeride shape',
    waist: 108,
    tagline: 'One pair. A lot of possibilities.',
    description: 'The 108 mm MVP brings freeride versatility to a broad range of snow conditions, with an Enduro core and a beautifully understated birch veneer top.',
    custom: 'mvp-108',
  },
  {
    id: 'jedi-mind-sticks',
    name: 'Jedi Mind Sticks',
    price: 900,
    source: 'https://www.praxisskis.com/skis/jedi-mind-sticks/',
    photos: ['jedi-mind-sticks-3.jpg', 'jedi-mind-sticks-0.jpg', 'jedi-mind-sticks-1.jpg', 'jedi-mind-sticks-2.jpg'],
    lengths: [174, 182, 190],
    terrain: ['Powder', 'All mountain'],
    veneer: 'Poplar',
    core: 'Maple, ash & aspen',
    flex: '4',
    profile: 'Stage 2 rocker',
    tagline: 'Find your own line.',
    description: 'Developed with Jedidiah Kravitz, the Jedi Mind Sticks combine a playful freeride shape with a supportive Enduro core for creative skiing in soft snow.',
    custom: 'jedi-mind-sticks',
  },
  {
    id: 'rx',
    name: 'RX',
    price: 900,
    source: 'https://www.praxisskis.com/skis/rx/',
    photos: ['rx-1.jpg', 'rx-0.jpg', 'rx-2.jpg', 'rx-3.jpg'],
    lengths: [169, 179, 184, 189],
    terrain: ['Powder'],
    veneer: 'Bubinga',
    core: 'Maple, ash & aspen',
    flex: '4',
    profile: 'Directional shape, slight tail rocker',
    waist: 116,
    tagline: 'Room to open it up.',
    description: 'A 116 mm freeride ski with a longer sidecut and a preference for big, open turns. A richly colored bubinga veneer makes the RX distinctive before the first run.',
    custom: 'rx',
  },
  {
    id: 'frs',
    name: 'FRS',
    price: 900,
    source: 'https://www.praxisskis.com/skis/frs/',
    photos: ['frs-2.jpg', 'frs-0.jpg', 'frs-1.jpg', 'frs-3.jpg'],
    lengths: [176, 182, 188, 194],
    terrain: ['Powder', 'All mountain'],
    veneer: 'Maple burl',
    core: 'Maple, ash & aspen',
    flex: '4',
    profile: 'Rocker–camber–rocker',
    tagline: 'Freeride, in full expression.',
    description: 'A broad freeride platform developed from the custom MVP family, with an Enduro core and expressive maple burl grain across the topsheet.',
    custom: 'frs',
  },
  {
    id: 'protest',
    name: 'Protest',
    price: 900,
    source: 'https://www.praxisskis.com/skis/protest/',
    photos: ['protest-1.jpg', 'protest-0.jpg', 'protest-2.jpg', 'protest-3.jpg'],
    lengths: [163, 177, 187, 192, 196],
    terrain: ['Powder'],
    veneer: 'Ambrosia maple',
    core: 'Maple, ash & aspen',
    flex: '3',
    profile: 'Stage 2 rocker, hybrid sidecut',
    tagline: 'A different kind of powder day.',
    description: 'A powder-focused shape with a hybrid five-point sidecut and a softer flex. The Protest is built for fluid turns and a loose, surf-inspired feel in deep snow.',
    custom: 'protest',
  },
  {
    id: 'valkyrie',
    name: 'Valkyrie',
    price: 999,
    preorder: true,
    source: 'https://www.praxisskis.com/skis/valkyrie/',
    photos: ['valkyrie-0.jpg'],
    lengths: [160, 166, 172, 178],
    terrain: ['All mountain', 'Carving'],
    veneer: 'Samantha Adams artwork',
    core: 'Maple, ash & aspen',
    flex: 'See Praxis',
    profile: 'All-mountain shape',
    waist: 100,
    tagline: 'A new chapter on the mountain.',
    description: 'Created with She-Shredz, the Valkyrie is a 100 mm all-mountain ski featuring Samantha Adams artwork. The current Praxis listing is a preorder.',
    custom: null,
  },
];
