import {brands} from '../src/catalog.js';
import {engravingPrice} from '../src/grass-options.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {createEngine} from '@rivet/configurator/engine';
import {createPack,proofKey} from '../src/pack.js';
import {generateSkiMesh,meshReport} from '@rivet/ski-geometry';
import {parsePriceCsv} from '../src/admin-data.js';
const engine=id=>createEngine(createPack(id));
test('Folsom validates length and rocker when switching shapes',()=>{const e=engine('folsom');const c=e.normalize({model:'completo-100',length:180,profile:'Powder Rocker',layup:'tour'});assert.equal(e.total(c).amount,1850);const changed=e.apply(c,{model:'spar-98'});assert.equal(changed.config.length,null);assert.equal(changed.config.profile,'Traditional Rocker');assert.equal(changed.config.layup,'tour');assert.equal(e.ready(changed.config),false);assert.ok(changed.changes.length>=2);});
test('Folsom encodes and restores valid product choices',()=>{const e=engine('folsom'),c=e.normalize({model:'spar-98',length:182,profile:'Directional Rocker',graphic:'magma',tail:'Flat',layup:'aggressive'});assert.deepEqual(e.decode(e.encode(c)).config,c);assert.equal(e.total(c).amount,1650);assert.match(e.text(c),/Magma/);});
test('All ski models and lengths produce finite closed mesh data',()=>{for(const id of ['folsom','meier']){const e=engine(id);for(const model of brands[id].models){const c=e.normalize({model:model.id});for(const length of e.context(c).lengths){const sized={...c,length},shape=e.pack.model3d.shape(sized,e.context(sized)),mesh=generateSkiMesh(shape);assert.ok(mesh.positions.every(p=>p.every(Number.isFinite)));assert.equal(meshReport(mesh).open,0);for(let i=1;i<10000;i++){const u=i/10000;assert.ok(Math.abs(shape.widthAt(u+1e-7)-shape.widthAt(u-1e-7))<.01,model.id+' has a disconnected outline');}}}}});
test('Meier uploaded art cannot be reviewed without a local file',()=>{const e=engine('meier'),c=e.normalize({model:'doc',length:179,design:'upload'});assert.equal(e.total(c).amount,1495);assert.ok(e.missingForOrder(c).some(m=>m.label.includes('artwork')));assert.ok(!e.encode({...c,artId:'private-id',artFile:'private.png',brief:'private story'}).includes('private'));});
test('Meier changing shape or graphic invalidates approved proof, including restored values',()=>{const e=engine('meier');let c=e.normalize({model:'doc',length:179});c=e.apply(c,{proof:proofKey(c)}).config;assert.ok(c.proof);assert.equal(e.missingForOrder(c).length,0);assert.equal(e.apply(c,{graphic:'quickdraw'}).config.proof,'');assert.equal(e.normalize({...c,length:184}).proof,'');});
test('Meier artist brief has a review gate and correct pricing',()=>{const e=engine('meier');let c=e.normalize({model:'quickdraw',length:173,design:'artist'});assert.equal(e.total(c).amount,1495);assert.ok(e.missingForOrder(c).some(m=>m.label.includes('brief')));c=e.apply(c,{brief:'Green peaks, visible wood, our favorite mountain.'}).config;c=e.apply(c,{proof:proofKey(c)}).config;assert.equal(e.missingForOrder(c).length,0);});
test('Grass Sticks totals, custom size and unavailable baskets survive shared link validation',()=>{const e=engine('grass');const c=e.normalize({model:'original',length:123.5,grip:'cork',basketColor:'pink',basket:'powder',strap:'adjustable'});assert.equal(c.basket,'medium');assert.equal(e.total(c).amount,158.95);assert.equal(e.decode(e.encode(c)).config.length,123.5);assert.equal(e.total(e.apply(c,{strap:'none'}).config).amount,145.95);assert.equal(e.normalize({model:'original',length:0}).length,120);});
test('Admin updates prices and disabled items in the same validation path',()=>{const e=createEngine(createPack('folsom',{overrides:{'model:completo-100':{price:1750,enabled:false},'model:spar-98':{price:1700,enabled:true},'graphic:japow':{price:0,enabled:false}}}));assert.equal(e.defaults().model,'');assert.notEqual(e.defaults().graphic,'japow');assert.equal(e.normalize({model:'completo-100',length:182}).model,'');assert.equal(e.total(e.normalize({model:'spar-98',length:182})).amount,1700);});
test('CSV import rejects invalid, duplicate and unknown entries before publication',()=>{assert.deepEqual(parsePriceCsv('key,price,enabled\nmodel:doc,1200,true','meier'),{'model:doc':{price:1200,enabled:true}});for(const text of ['key,price,enabled\nmodel:doc,-1,true','key,price,enabled\nunknown,1,true','key,price,enabled\nmodel:doc,1,true\nmodel:doc,2,true','key,price,enabled\n'+brands.meier.models.map(m=>'model:'+m.id+',1099,false').join('\n')])assert.throws(()=>parsePriceCsv(text,'meier'));});

test('Full sourced catalogs remain reachable through their families',()=>{assert.equal(brands.folsom.models.length,23);assert.equal(brands.meier.models.length,21);assert.equal(brands.grass.models.length,12);for(const id of ['folsom','meier','grass']){const e=engine(id);for(const m of brands[id].models){const c=e.normalize({model:m.id,length:m.lengths[0]});assert.equal(c.model,m.id);assert.ok(e.options(e.group('model'),c).some(o=>o.value===m.id));assert.deepEqual(e.decode(e.encode(c)).config,c);}}});
test('Folsom dimensions, length availability and junior construction follow the model',()=>{const e=engine('folsom');for(const [length,waist] of [[146,86],[154,95]]){const c=e.normalize({model:'hayden',length,layup:'tour'});assert.equal(c.layup,'junior');assert.equal(e.total(c).amount,550);assert.equal(e.pack.model3d.shape(c,e.context(c)).waistMm,waist);}assert.equal(e.normalize({model:'cash-93',length:190}).length,null);assert.equal(e.normalize({model:'g-wagon',tail:'Flat'}).tail,'Round');});
test('Family changes clear incompatible shape and size',()=>{const e=engine('folsom'),c=e.normalize({model:'spar-98',length:186});const next=e.apply(c,{family:'completo'}).config;assert.equal(next.model,'');assert.equal(next.length,null);assert.equal(next.family,'completo');});
test('Grass products enforce their own choices and do not leak option prices',()=>{const e=engine('grass');let c=e.normalize({model:'touring',length:130,basket:'tiny',basketColor:'pink',grip:'cork',strap:'mtn'});assert.equal(c.basketColor,'black');assert.equal(e.total(c).amount,180.94);c=e.apply(c,{model:'kids',length:140}).config;assert.equal(c.length,95);assert.equal(c.basket,'medium');c=e.apply(c,{model:'tip-covers'}).config;assert.equal(c.grip,'');assert.equal(c.strap,'');assert.equal(c.length,null);assert.equal(e.total(c).amount,12);assert.equal(e.ready(c),true);assert.equal(e.total(e.normalize({model:'trekking',quantityType:'single'})).amount,89.95);});
test('Grass gifts, engraving and growth service have complete review data',()=>{const e=engine('grass');const gift=e.normalize({model:'gift-kids',giftFormat:'physical',giftMtn:true,giftHat:true,giftCork:true});assert.equal(gift.giftCork,false);assert.equal(e.total(gift).amount,128.95);assert.equal(engravingPrice('1234567'),15.25);const engraved=e.normalize({model:'original',engraving1:'1234567',engraving2:'ABC'});assert.equal(e.total(engraved).amount,164.2);assert.ok(e.text(engraved).includes('1234567'));assert.ok(!e.encode(engraved).includes('1234567'));let service=e.normalize({model:'length-change'});assert.equal(e.total(service).amount,14);assert.equal(service.basket,'reuse');assert.equal(e.missingForOrder(service).length,1);service=e.apply(service,{originalOrder:'demo-order-100'}).config;assert.equal(e.missingForOrder(service).length,0);});

test('Norheim retains an asymmetric silhouette and mirrored pair',()=>{const e=engine('meier'),c=e.normalize({model:'norheim-telemark-skis-1',length:180}),shape=e.pack.model3d.shape(c,e.context(c));assert.equal(shape.mirrorPair,true);assert.ok(Math.abs(shape.centerAt(.015))>1);assert.equal(generateSkiMesh(shape).definition.mirrorPair,true);});


test('Folsom separates Profile, Construction and Bindings into their own steps',()=>{const e=engine('folsom');assert.deepEqual(e.steps.map(s=>s.id),['shape','profile','art','build','bindings','review']);assert.deepEqual(e.stepGroups('shape').map(g=>g.id),['family','model','length']);assert.deepEqual(e.stepGroups('profile').map(g=>g.id),['profile','tail']);assert.deepEqual(e.stepGroups('bindings').map(g=>g.id),['binding']);assert.deepEqual(e.stepGroups('build').map(g=>g.id),['layup']);const c=e.normalize({model:'cash-106',length:189,profile:'Everyday Rocker',tail:'Flat',layup:'tour'}),changed=e.apply(c,{profile:'Shallow Reverse Camber'}).config;assert.deepEqual(e.invalidateReviews(c,changed,[0,1,2,3,4]),[0,2,3,4]);assert.equal(e.bom(changed).find(l=>l.key==='profile').step,1);assert.equal(e.bom(changed).find(l=>l.key==='tail').step,1);assert.equal(e.total(changed).amount,1850);});

test('Every Folsom gallery entry has selectable artwork, both textures and a source',async()=>{const {stat}=await import('node:fs/promises'),e=engine('folsom'),catalog=brands.folsom.graphicCatalog;assert.equal(catalog.art.length,174);assert.equal(catalog.categories.length,11);assert.equal(new Set(catalog.art.map(a=>a.id)).size,174);assert.equal(e.defaults().graphic,'japow');for(const a of catalog.art){assert.ok(a.source.startsWith('https://www.folsomskis.com/'));assert.ok(a.categories.every(id=>catalog.categories.some(c=>c.id===id)));const c=e.normalize({model:'spar-98',length:186,graphic:a.id});assert.equal(c.graphic,a.id);assert.equal(e.decode(e.encode(c)).config.graphic,a.id);for(const suffix of ['.jpg','-l.webp','-r.webp'])assert.ok((await stat(new URL('../public/brands/folsom/'+a.id+suffix,import.meta.url))).size>100);}});


test('Folsom rocker profiles change the side elevation and describe every choice',()=>{const e=engine('folsom'),c=e.normalize({model:'cash-106',length:189}),ctx=e.context(c),profiles=e.options(e.group('profile'),c);const curves=profiles.map(p=>{assert.ok(p.text.length>50);const shape=e.pack.model3d.shape({...c,profile:p.value},ctx);return [0,.1,.25,.5,.8,1].map(shape.heightAt);});assert.equal(new Set(curves.map(v=>JSON.stringify(v))).size,profiles.length);assert.ok(curves.at(-1)[3]<.001);assert.ok(curves[0][3]>0);assert.equal(e.pack.viewForField('',1),'Profile');assert.equal(e.pack.model3d.views.find(v=>v.value==='Profile').camera,'profile');for(const o of e.options(e.group('tail'),c))assert.ok(o.text.length>40);const round=e.pack.model3d.shape({...c,tail:'Round'},ctx),flat=e.pack.model3d.shape({...c,tail:'Flat'},ctx);assert.ok(flat.widthAt(1)>round.widthAt(1));});
test('Marker choices update totals, shared links, exports, removal and catalog availability',()=>{const e=engine('folsom');let c=e.normalize({model:'cash-106',length:189,binding:'marker-squire'});assert.equal(e.total(c).amount,1880);assert.equal(e.bom(c).find(x=>x.key==='binding').step,4);assert.match(e.text(c),/Marker Squire/);assert.deepEqual(e.decode(e.encode(c)).config,c);c=e.apply(c,{binding:'marker-jester'}).config;assert.equal(e.total(c).amount,2050);assert.match(e.pack.model3d.binding(c.binding).url,/marker-jester.glb$/);c=e.apply(c,{binding:''}).config;assert.equal(e.total(c).amount,1650);assert.equal(e.pack.model3d.binding(c.binding),null);const custom=createEngine(createPack('folsom',{overrides:{'binding:marker-squire':{enabled:false},'binding:marker-jester':{price:425}}}));assert.equal(custom.normalize({...c,binding:'marker-squire'}).binding,'');assert.equal(custom.total(custom.normalize({...c,binding:'marker-jester'})).amount,2075);assert.deepEqual(parsePriceCsv('key,price,enabled\nbinding:marker-squire,230,false','folsom'),{'binding:marker-squire':{price:230,enabled:false}});});
test('Both Marker Blender exports contain distinct renderable meshes and materials',async()=>{const {readFile}=await import('node:fs/promises');const assets=[];for(const id of ['squire','jester']){const data=await readFile(new URL('../public/brands/folsom/bindings/marker-'+id+'.glb',import.meta.url));assert.equal(data.readUInt32LE(0),0x46546c67);const gltf=JSON.parse(data.subarray(20,20+data.readUInt32LE(12)).toString());assert.ok(gltf.meshes.length>50);assert.ok(gltf.materials.some(m=>m.name.includes('Stainless')));assert.ok(gltf.nodes.some(n=>n.name.includes('Heel')));assets.push(data);}assert.ok(!assets[0].equals(assets[1]));});
