import React,{Suspense,lazy,useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight,ArrowUpRight,SlidersHorizontal,Check,ArrowLeft} from 'lucide-react';
import {Configurator,createEngine} from '@rivet/configurator';
import '@rivet/configurator/styles.css';
import '@rivet/configurator/studio3d.css';
import './theme.css';
import {brands,asset} from './catalog.js';
import {createPack} from './pack.js';
import {widgets} from './widgets.jsx';
import {readOverrides} from './admin-data.js';
const PoleStage=lazy(()=>import('./PoleStage.jsx'));
const Admin=lazy(()=>import('./Admin.jsx'));
const GrassStage=props=><Suspense fallback={<div className="cfg-3d-loading">Preparing your bamboo poles…</div>}><PoleStage {...props}/></Suspense>;
function Hub(){return <main className="review-hub"><header><a className="studio-wordmark" href="#/">CUSTOM / STUDIO</a><a href="#/admin" className="hub-admin"><SlidersHorizontal size={15}/> Catalog controls</a></header><div className="hub-intro"><p className="eyebrow">FIRST WAVE · PRIVATE REVIEW</p><h1>Different makers.<br/>Entirely their own.</h1><p>Four custom experiences, built around how each brand makes and sells its products.</p></div><div className="demo-grid">{[{id:'praxis',name:'Praxis',tag:'The full custom workshop',description:'22 shapes, wood veneers, artwork, core and flex tuning, bindings and a saved demo bag.',href:'./praxis/#/custom'},...Object.values(brands).map(b=>({id:b.id,name:b.name,tag:b.tag,description:b.id==='folsom'?'23 shapes across six families, with original artwork and model-specific build choices.':b.id==='meier'?'21 shapes across the current terrain and Secret Stash collections, with house or custom artwork.':'All 12 shop products: five pole models, accessories, gifts and the kids’ growth service.',href:`#/${b.id}`}))].map(b=><a className={`demo-card demo-${b.id}`} href={b.href} key={b.id}><div className="demo-card-visual">{b.id==='praxis'?<span className="praxis-word">PRAXIS</span>:<img className="demo-logo" src={asset(`${b.id}/logo.png`)} alt={b.name}/>}<div className="demo-object">{b.id==='folsom'?<img src={asset('folsom/japow.jpg')} alt="Folsom Japow skis"/>:b.id==='meier'?<img src={asset('meier/quickdraw.jpg')} alt="Meier wood-core skis"/>:b.id==='grass'?<img src={asset('grass/poles.jpg')} alt="Grass Sticks bamboo poles"/>:<span>Handcrafted<br/><i>in Tahoe.</i></span>}</div></div><div className="demo-card-info"><small>{b.tag}</small><h2>{b.name}<ArrowUpRight size={25}/></h2><p>{b.description}</p><span className="demo-open">Open demo <ArrowRight size={14}/></span></div></a>)}</div><footer><p>Independent outreach concepts · Public product information observed September 2026.<br/>Builds save on this device. No orders, payments or messages are submitted.</p><a href="https://wellesruhlin.com/demos/CPQ/ON3P/" target="_blank" rel="noreferrer">ON3P benchmark <ArrowUpRight size={13}/></a></footer></main>;}
function Demo({id}){
 const brand=brands[id];const [reviewedBuild,setReviewedBuild]=useState(null);
 const engine=useMemo(()=>createEngine(createPack(id,{widgets,Stage:GrassStage,overrides:readOverrides(id)})),[id]);
 const link=useMemo(()=>({read:()=>location.hash.split('?')[1]||null,url:encoded=>`${location.origin}${location.pathname}#/${id}?${encoded}`,listen:fn=>{const handler=()=>{if(location.hash.startsWith(`#/${id}?`))fn(location.hash.split('?')[1]);};addEventListener('hashchange',handler);return()=>removeEventListener('hashchange',handler);}}),[id]);
 const guides={how:{title:`Your ${brand.name} custom build`,render:()=> <div className="brand-guide"><p>{id==='grass'?'Explore poles, accessories, gifts and the kids’ growth program. Each product shows its own available options.':id==='meier'?'Choose a shape, then select a house graphic, upload your artwork or write a brief for an artist. Review the design before saving.':'Choose your model and length, then tune rocker and tail shape in Profile. Explore the full graphics library, choose construction and add optional Marker bindings.'}</p><p>Prices update with your choices. Save a draft, copy a build link or download the specification sheet. A saved review is local to this browser.</p><p>This independent concept uses a snapshot of public product information. The brand confirms availability, production details and the final price.</p><a href={brand.source} target="_blank" rel="noreferrer">View the maker’s current custom program ↗</a></div>}};
 useEffect(()=>{if(!reviewedBuild)return;const handler=e=>{if(e.key==='Escape')setReviewedBuild(null);if(e.key==='Tab'){const items=[...document.querySelectorAll('.review-confirm button,.review-confirm a')];if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0]?.focus();}}};addEventListener('keydown',handler);return()=>removeEventListener('keydown',handler);},[reviewedBuild]);
 useEffect(()=>{document.title=`${brand.name} · Custom Studio`;window.scrollTo(0,0);},[brand]);
 return <><Configurator key={id} engine={engine} storageKey={`first-wave-${id}-build`} link={link} guides={guides} header={(nav,actions)=><header className="brand-header"><a href="#/" className="brand-home" aria-label="Back to demo collection"><img src={asset(`${id}/logo.png`)} alt={brand.name}/><span>Custom {id==='grass'?'sticks':'shop'}</span></a>{nav}{actions}</header>} finalAction={{label:'Save for review',run:(config,{engine,notify,goTo})=>{const missing=engine.missingForOrder(config);if(missing.length){notify(`Please ${missing[0].label}.`);goTo(missing[0].step);return;}try{localStorage.setItem(`first-wave-${id}-review`,JSON.stringify({config,total:engine.total(config).amount,saved:new Date().toISOString()}));localStorage.setItem(`first-wave-${id}-build`,JSON.stringify({version:2,reviewVersion:engine.pack.reviewVersion,config,reviewed:engine.steps.slice(0,-1).map((_,i)=>i)}));setReviewedBuild(config);}catch{notify('Storage is unavailable. Download your build sheet from Review.');}}}}/>{reviewedBuild&&<div className="review-overlay" role="dialog" aria-modal="true" aria-labelledby="review-title"><div className="review-confirm"><Check size={30}/><p className="eyebrow">SAVED ON THIS DEVICE</p><h2 id="review-title">Your build is ready.</h2><p>{engine.context(reviewedBuild).model.name}{reviewedBuild.length?` · ${reviewedBuild.length} cm`:''}<br/>{engine.money(engine.total(reviewedBuild).amount)} reference total</p><p>You can keep refining it or return to the demo collection. No order has been placed.</p><button autoFocus onClick={()=>setReviewedBuild(null)}>Back to your build</button><a href="#/" onClick={()=>setReviewedBuild(null)}>Explore the other demos <ArrowRight size={14}/></a></div></div>}</>;
}
function App(){const [route,setRoute]=useState(location.hash.split('?')[0].replace('#/',''));useEffect(()=>{const change=()=>setRoute(location.hash.split('?')[0].replace('#/',''));addEventListener('hashchange',change);return()=>removeEventListener('hashchange',change);},[]);return route==='admin'?<Suspense fallback={<p>Loading catalog controls…</p>}><Admin/></Suspense>:brands[route]?<Demo id={route}/>:<Hub/>;}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
