import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {Minus,Plus,RotateCcw} from 'lucide-react';
import {RadioGroup} from '@arc/configurator';
import {brands,colors,title,asset} from './catalog.js';

import {strapDesigns} from '@arc/brand-grass-sticks';

function bambooTexture(torched=false){const c=document.createElement('canvas');c.width=256;c.height=1024;const p=c.getContext('2d');p.fillStyle='#caaa69';p.fillRect(0,0,256,1024);for(let x=0;x<256;x++){p.strokeStyle=`rgba(87,57,18,${.025+(Math.sin(x*71)+1)*.025})`;p.beginPath();p.moveTo(x,0);p.lineTo(x+Math.sin(x)*2,1024);p.stroke();}for(const y of [130,362,600,844]){p.fillStyle='#aa864c';p.fillRect(0,y,256,3);p.fillStyle='#e1c795';p.fillRect(0,y+4,256,3);}if(torched)for(let y=55;y<1024;y+=95){const gradient=p.createLinearGradient(0,y-14,0,y+14);gradient.addColorStop(0,'#b58b48');gradient.addColorStop(.4,'#382215');gradient.addColorStop(.65,'#523019');gradient.addColorStop(1,'#b58b48');p.fillStyle=gradient;p.fillRect(0,y-14,256,28);}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function makePole(c,x){const g=new THREE.Group();g.position.x=x;const L=c.length/100;const mat=(color='#202426',roughness=.62)=>new THREE.MeshStandardMaterial({color,roughness});const bamboo=new THREE.MeshStandardMaterial({map:bambooTexture(c.model==='ringtail'),roughness:.62});
 const add=(geo,m,y)=>{const mesh=new THREE.Mesh(geo,m);mesh.position.y=y;g.add(mesh);return mesh;};
 add(new THREE.CylinderGeometry(.0078,.006,L-.115,40),bamboo,(L-.115)/2+.035);
 if(c.model==='touring')add(new THREE.CylinderGeometry(.012,.012,.165,32),mat('#282b26'),L-.26);
 for(let y=.19;y<L-.16;y+=.235)add(new THREE.CylinderGeometry(.0081,.0081,.003,32),mat('#c6a674'),y);
 const grip=mat(colors[c.grip]||'#202426',c.grip==='cork'?.95:.75);const profile=[[.013,0],[.018,.005],[.016,.012],[.012,.023],[.013,.038],[.012,.053],[.013,.069],[.012,.085],[.014,.11],[.017,.119],[.017,.127],[.014,.133]].map(([r,y])=>new THREE.Vector2(r,y));
 add(new THREE.LatheGeometry(profile,48),grip,L-.135);
 for(let y=L-.105;y<L-.025;y+=.006)add(new THREE.TorusGeometry(.0127,.00065,5,36),mat(c.grip==='cork'?'#96734d':colors[c.grip]),y).rotation.x=Math.PI/2;
 if(c.strap!=='none'){const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(0,L-.015,0),new THREE.Vector3(.052,L-.04,.015),new THREE.Vector3(.045,L-.15,.028),new THREE.Vector3(.005,L-.125,.01),new THREE.Vector3(0,L-.015,0)]);const geo=new THREE.TubeGeometry(curve,64,.003,6,false);const strapMat=mat(c.strap==='mtn'?'#ffffff':'#b5a880');if(c.strap==='mtn'){strapMat.map=new THREE.TextureLoader().load(asset('grass/strap-'+Math.max(0,strapDesigns.indexOf(c.strapDesign))+'.webp'));strapMat.map.colorSpace=THREE.SRGBColorSpace;}const strap=add(geo,strapMat,0);strap.scale.z=1.7;}
 const basket=new THREE.Shape(),radius=c.basket==='tiny'?.0254:c.basket==='powder'?.0603:.0508;for(let i=0;i<=96;i++){const angle=i/96*Math.PI*2;const r=radius*(1-.045*Math.cos(angle*12));const a=Math.cos(angle)*r,b=Math.sin(angle)*r;i?basket.lineTo(a,b):basket.moveTo(a,b);}for(let i=0;i<8;i++){const a=i*Math.PI/4;const hole=new THREE.Path();hole.absellipse(Math.cos(a)*radius*.55,Math.sin(a)*radius*.55,radius*.118,radius*.236,0,Math.PI*2,true,a-Math.PI/2);basket.holes.push(hole);}const basketMesh=add(new THREE.ExtrudeGeometry(basket,{depth:.003,bevelEnabled:true,bevelSegments:2,steps:1,bevelSize:.001,bevelThickness:.001}),mat(colors[c.basketColor]||'#202426'),.063);basketMesh.rotation.x=-Math.PI/2;
 add(new THREE.CylinderGeometry(.009,.007,.012,24),mat(colors[c.basketColor]),.063);
 add(new THREE.CylinderGeometry(.006,.003,.046,24),mat('#303334'),.024);add(new THREE.ConeGeometry(.003,.011,24),mat('#899195',.25),-.004).rotation.z=Math.PI;
 const labelCanvas=document.createElement('canvas');labelCanvas.width=128;labelCanvas.height=512;const ctx=labelCanvas.getContext('2d');ctx.translate(64,256);ctx.rotate(-Math.PI/2);ctx.fillStyle='#403b26';ctx.font='bold 27px Arial';ctx.textAlign='center';ctx.fillText('GRASS STICKS',0,8);const labelMat=new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(labelCanvas),transparent:true,depthWrite:false});const label=add(new THREE.PlaneGeometry(.024,.096),labelMat,L-.255);label.position.z=.0081;
 return g;
}
function BambooStage({config,view,onView}){
 const host=useRef(null),rt=useRef(null);const [error,setError]=useState('');
 useEffect(()=>{let renderer,frame;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;host.current.append(renderer.domElement);renderer.domElement.setAttribute('aria-label','Interactive bamboo pole preview');const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(30,1,.01,20);const control=new OrbitControls(camera,renderer.domElement);control.enableDamping=true;control.enablePan=false;control.minDistance=.13;control.maxDistance=5;scene.add(new THREE.HemisphereLight('#ffffff','#c5b69b',2.6));const key=new THREE.DirectionalLight('#ffffff',3);key.position.set(2,3,4);scene.add(key);const back=new THREE.DirectionalLight('#dceaf0',2);back.position.set(-2,1,-2);scene.add(back);const group=new THREE.Group();scene.add(group);const resize=()=>{const box=host.current.getBoundingClientRect();renderer.setSize(box.width,box.height);camera.aspect=box.width/Math.max(1,box.height);camera.updateProjectionMatrix();};const ro=new ResizeObserver(resize);ro.observe(host.current);resize();rt.current={scene,camera,control,group,reset:()=>{const h=Number(renderer.domElement.dataset.length)||1.2;const mode=renderer.domElement.dataset.view;const focus=mode==='Grip'?h-.075:mode==='Basket'?.065:h*.5;const dist=mode==='Grip'?.48:mode==='Basket'?.45:Math.max(2.5,h*2.3);camera.position.set(mode==='3D'?.7:0,focus,dist);control.target.set(0,focus,0);control.enableRotate=mode==='3D';control.update();}};const tick=()=>{control.update();renderer.render(scene,camera);frame=requestAnimationFrame(tick);};tick();return()=>{cancelAnimationFrame(frame);ro.disconnect();control.dispose();scene.traverse(o=>{o.geometry?.dispose();if(o.material){o.material.map?.dispose();o.material.dispose();}});renderer.dispose();renderer.domElement.remove();rt.current=null;};}catch{setError('The 3D preview could not start. Try reloading with WebGL enabled.');}},[]);
 useEffect(()=>{const r=rt.current;if(!r)return;for(const child of [...r.group.children]){child.traverse(o=>{o.geometry?.dispose();o.material?.map?.dispose();o.material?.dispose();});r.group.remove(child);}(config.quantityType==='single'?[0]:[-.083,.083]).forEach(x=>r.group.add(makePole(config,x)));const canvas=host.current.querySelector('canvas');canvas.dataset.length=config.length/100;canvas.dataset.view=view;r.reset();},[config.model,config.length,config.grip,config.basketColor,config.basket,config.strap,config.strapDesign,config.quantityType,view]);
 const views=[{value:'Topsheet',label:config.quantityType==='single'?'Full pole':'Full pair'},{value:'Grip',label:'Grips'},{value:'Basket',label:'Baskets'},{value:'3D',label:'3D'}];return <section className="pole-studio" aria-label="Grass Sticks 3D preview"><div className="pole-stage"><div className="cfg-3d-heading"><p className="cfg-overline">{brands.grass.origin}</p><h2>{brands.grass.models.find(m=>m.id===config.model)?.name}</h2><p className="cfg-3d-lead">{brands.grass.models.find(m=>m.id===config.model)?.summary}</p><p className="cfg-3d-finish">{title(config.grip)} grips · {config.basket==='reuse'?'Reuse your baskets':title(config.basketColor)+' baskets'}</p></div><div className="pole-canvas" ref={host}/>{error&&<p role="alert">{error}</p>}<p className="pole-hint">{view==='3D'?'Drag to orbit · ':''}Scroll to zoom · natural bamboo varies</p><div className="pole-zoom"><button aria-label="Zoom out" onClick={()=>{rt.current.camera.position.sub(rt.current.control.target).multiplyScalar(1.2).add(rt.current.control.target);}}><Minus size={16}/></button><button aria-label="Reset view" onClick={()=>rt.current?.reset()}><RotateCcw size={16}/></button><button aria-label="Zoom in" onClick={()=>{rt.current.camera.position.sub(rt.current.control.target).multiplyScalar(.8).add(rt.current.control.target);}}><Plus size={16}/></button></div></div><div className="cfg-3d-footer"><RadioGroup label="Preview view" className="cfg-segmented is-glass" options={views} value={view} onChange={onView}/></div></section>;
}

export default function PoleStage(props){const model=brands.grass.models.find(m=>m.id===props.config.model);if(model?.kind==='poles'||model?.kind==='service')return <BambooStage key={model.id} {...props}/>;return <section className="grass-product-stage" aria-label="Product preview"><div className="cfg-3d-heading"><p className="cfg-overline">{brands.grass.origin}</p><h2>{model?.name||'Find your Sticks'}</h2><p className="cfg-3d-lead">{model?.summary||'Ski poles, trail companions and the gear that keeps them going. Made by hand, made for you.'}</p></div><img className="grass-product-photo" src={asset('grass/'+(model?.id==='mtn-straps'?'strap-'+Math.max(0,strapDesigns.indexOf(props.config.strapDesign))+'.webp':model?.image||'poles.jpg'))} alt={model?.name||'Grass Sticks collection'}/>{model&&<div className="grass-product-notes"><p>{model.kind==='gift'?'A gift card preview. Your recipient chooses the finished poles.':model.id==='coat-kit'?'Everything needed to touch up the clear finish.':model.id==='tip-covers'?'Rubber covers press onto your existing pole tips.':model.id==='baskets'?`Basket color collection · selected: ${title(props.config.basketColor)}. Medium pair; other sizes are currently unavailable.`:props.config.strapDesign?props.config.strapDesign+' · selected strap design':''}</p><a href={model.source} target="_blank" rel="noreferrer">Product details from Grass Sticks ↗</a></div>}</section>;}


