import {useState} from 'react';
import {Check,Upload,ArrowUpRight} from 'lucide-react';
import {RadioGroup} from '@arc/configurator';
import {asset,brands} from './catalog.js';
import {proofKey} from './pack.js';
import {storedArt} from './ski3d.js';
import {strapDesigns} from '@arc/brand-grass-sticks';
import {folsomBindings} from '@arc/brand-folsom';

export function TailShapes({engine,group,config,update}){
 const paths={Round:'M10 2V24Q10 45 28 45Q46 45 46 24V2',Flat:'M10 2V40Q10 43 13 43H43Q46 43 46 40V2',Touring:'M10 2V40H24V35H32V40H46V2',Swallowtail:'M10 2V43L28 26L46 43V2'};
 return <RadioGroup label="Tail shape" className="folsom-tail-grid" itemClassName="folsom-tail-card" options={engine.options(group,config)} value={config.tail} onChange={tail=>update({tail})} render={(o,checked)=><><svg viewBox="0 0 56 50" aria-hidden="true"><path d={paths[o.value]||paths.Round}/></svg><span><strong>{o.label}</strong><small>{o.text}</small></span>{checked&&<Check size={14}/>}</>}/>;
}
export function FolsomBindings({engine,group,config,update,onView,binding}){
 const options=[{value:'',label:'No bindings'},...engine.options(group,config)];
 return <><RadioGroup label="Bindings" className="folsom-binding-grid" itemClassName="folsom-binding-card" options={options} value={config.binding} onChange={value=>{binding.setPreview(null);update({binding:value});onView(value?'Bindings':'Topsheet');}} render={(o,checked)=>{const b=folsomBindings.find(b=>b.id===o.value);return <>{b?<img src={asset(`folsom/bindings/${b.id}.jpg`)} alt=""/>:<span className="folsom-skis-only" aria-hidden="true">—</span>}<span><strong>{o.label}</strong><small>{b?o.text:'Bring your own bindings. No added cost.'}</small>{b&&<b>+{engine.money(group.price(b.id))}</b>}</span>{checked&&<Check size={15}/>}</>;}}/>
 <p className="field-note">Marker Griffon is temporarily sold out at Folsom.</p>
 {config.binding&&<p className="field-note">Shown in black. Folsom confirms the model year, color, brake width and boot compatibility with your order.</p>}
 </>;
}

export function Graphics({engine,group,config,update}){
 const [category,setCategory]=useState('all');
 const [query,setQuery]=useState('');
 const catalog=brands[engine.pack.id].graphicCatalog;
 const options=engine.options(group,config);
 const matches=new Set(catalog?.art.filter(a=>(category==='all'||a.categories.includes(category))&&a.name.toLowerCase().includes(query.trim().toLowerCase())).map(a=>a.id));
 const visible=catalog?options.filter(o=>matches.has(o.value)):options;
 const selected=options.find(o=>o.value===config.graphic);
 return <>
  {catalog&&<div className="art-library-tools">
   <label>Collection<select aria-label="Artwork collection" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All artwork · {catalog.art.length}</option>{catalog.categories.map(c=><option key={c.id} value={c.id}>{c.name} · {catalog.art.filter(a=>a.categories.includes(c.id)).length}</option>)}</select></label>
   <label>Search artwork<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name or artist"/></label>
   <div className="art-library-status"><p role="status">{visible.length} {visible.length===1?'design':'designs'}</p><p>Selected: <strong>{selected?.label||'None'}</strong></p></div>
  </div>}
  <RadioGroup label="Topsheet artwork" className="brand-art-grid" itemClassName="brand-art" options={visible} value={config.graphic} onChange={v=>update({graphic:v})} render={(o,checked)=><><img loading="lazy" decoding="async" src={asset(`${engine.pack.id}/${o.value}.jpg`)} alt=""/><span>{o.label}</span>{checked&&<Check size={14}/>}</>}/>
  {catalog&&!visible.length&&<div className="art-library-empty"><p>No artwork matches these filters.</p><button type="button" className="cfg-text-button" onClick={()=>{setCategory('all');setQuery('');}}>Show all artwork</button></div>}
 </>;
}
export function Swatches({engine,group,config,update}){return <><RadioGroup label={group.label} className="brand-colors" itemClassName="brand-color" options={engine.options(group,config)} value={config[group.id]} onChange={v=>update({[group.id]:v})} render={(o,checked)=><><i style={{background:o.color}}>{checked&&<Check size={17} color={['black','purple','blue'].includes(o.value)?'#fff':'#17310d'}/>}</i><span>{o.label}</span></>}/></>;}
export function Length({config,ctx,update}){const [unit,setUnit]=useState('cm');const [draft,setDraft]=useState(null);const [error,setError]=useState('');const max=ctx.model?.maxLength||200,min=ctx.model?.minLength||40;const value=unit==='cm'?config.length:Math.round(config.length/2.54*100)/100;const presets=max<110?[65,75,85,95,105]:[105,110,115,120,125,130,135];return <div className="pole-sizing"><div className="unit-choice"><button aria-pressed={unit==='cm'} onClick={()=>{setUnit('cm');setDraft(null);}}>Centimeters</button><button aria-pressed={unit==='in'} onClick={()=>{setUnit('in');setDraft(null);}}>Inches</button></div><div className="length-input"><input aria-label={'Pole length in '+(unit==='cm'?'centimeters':'inches')} type="number" step="0.1" min={unit==='cm'?min:min/2.54} max={unit==='cm'?max:max/2.54} value={draft??value} onChange={e=>{setDraft(e.target.value);const cm=Number(e.target.value)*(unit==='cm'?1:2.54);if(cm>=min&&cm<=max){update({length:Math.round(cm*100)/100});setError('');}else setError('Choose a length between '+min+' and '+max+' cm'+(max<110?' (42 inches maximum for Kids Sticks).':'.'));}} onBlur={()=>setDraft(null)}/><span>{unit}</span></div><div className="length-presets">{presets.map(n=><button key={n} aria-pressed={config.length===n} onClick={()=>{update({length:n});setDraft(null);setError('');}}>{unit==='cm'?n:(n/2.54).toFixed(1)}</button>)}</div>{error&&<p role="alert">{error}</p>}<p className="field-note">{max<110?'Kids Sticks are limited to 42 inches (106.68 cm).':'Measure from the tip to the top of the grip. Every shaft is cut to your chosen length.'}</p><a className="brand-source-link" href="https://www.grasssticks.com/skipolelengthcalc/" target="_blank" rel="noreferrer">Grass Sticks sizing guide <ArrowUpRight size={13}/></a></div>;}
export function Slider({group,config,update}){return <label className="brand-slider"><input aria-label={group.label} type="range" min={group.min} max={group.max} value={config[group.id]} onChange={e=>update({[group.id]:Number(e.target.value)})}/><output>{config[group.id]}%</output></label>;}
export function Brief({config,update}){return <><textarea aria-label="Design brief" maxLength={1200} value={config.brief} onChange={e=>update({brief:e.target.value})} placeholder="Tell us about your colors, places, stories and references…" rows={6}/><p className="field-note">Four hours of artist time are included. This brief stays on your device until you choose to share it with Meier.</p></>;}
export function UploadArt({config,update}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 const upload=async file=>{if(!file)return;setError('');if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>8*1024*1024){setError('Choose a PNG, JPG or WebP image under 8 MB.');return;}setBusy(true);try{const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');const ratio=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));canvas.width=Math.max(1,Math.round(bitmap.width*ratio));canvas.height=Math.max(1,Math.round(bitmap.height*ratio));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const pixels=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height);for(let i=0;i<pixels.data.length;i+=4){const white=Math.min(pixels.data[i],pixels.data[i+1],pixels.data[i+2]);if(white>220)pixels.data[i+3]*=(255-white)/35;}canvas.getContext('2d').putImageData(pixels,0,0);const id=crypto.randomUUID();localStorage.setItem(`studio-art-${id}`,canvas.toDataURL('image/webp',.88));update({artId:id,artFile:file.name});}catch{setError('The image could not be stored. Try a smaller file or allow browser storage.');}finally{setBusy(false);}};
 return <div><label className="upload-zone"><Upload size={22}/><strong>{busy?'Preparing your artwork…':config.artFile||'Add your artwork'}</strong><span>PNG, JPG or WebP · up to 8 MB</span><input type="file" aria-label="Upload topsheet artwork" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e.target.files?.[0])}/></label>{error&&<p role="alert">{error}</p>}{config.artId&&<button className="cfg-text-button" onClick={()=>update({artId:'',artFile:''})}>Remove artwork</button>}<p className="field-note">Preview only. White areas reveal the wood, as in Meier’s clear topsheet printing. Your file stays in this browser. Meier asks that roughly 30% of the design show the wood; a maker-approved print proof follows an actual order.</p></div>;
}
export function Proof({config,update}){const missing=config.design==='upload'&&!storedArt(config.artId)?'Add your artwork in the Artwork step first.':config.design==='artist'&&!config.brief.trim()?'Add your design brief in the Artwork step first.':'';const model=brands.meier.models.find(m=>m.id===config.model);return <div className="proof-card"><span className="proof-kicker">YOUR DESIGN CHECK</span><h3>{model?.name} · {config.length} cm</h3><p>{config.design==='artist'?'Review your design brief. The house graphic remains a placeholder until an artist creates your design.':'Inspect your skis in Front and 3D. Check your model, length and artwork before saving.'}</p>{config.design==='artist'&&<blockquote>{config.brief||'Your brief will appear here.'}</blockquote>}<label className="proof-check"><input type="checkbox" checked={!!config.proof} disabled={!!missing} onChange={e=>update({proof:e.target.checked?proofKey(config):''})}/><span>I have reviewed this {config.design==='artist'?'design brief':'design preview'}.</span></label>{missing&&<p role="status">{missing}</p>}<p className="field-note">Changing the shape, artwork or placement clears this check so an old proof cannot be approved by accident. This is a demo review, not production approval.</p></div>;}
export function ProductInfo({ctx}){return <div className="proof-card"><h3>{ctx.model.name}</h3><p>{ctx.model.summary}</p><p>This product has no additional configuration choices. Continue to Review to save it to your build sheet.</p><a href={ctx.model.source} target="_blank" rel="noreferrer">View care and product details ↗</a></div>;}
export function StrapPicker({engine,group,config,update}){return <RadioGroup label={group.label} className="strap-grid" options={engine.options(group,config)} value={config.strapDesign} onChange={value=>update({strapDesign:value})} render={(o,checked)=><><img src={asset(`grass/strap-${strapDesigns.indexOf(o.value)}.webp`)} alt=""/><span>{o.label}{checked&&<Check size={13}/>}</span></>}/>;}
export const widgets={graphics:Graphics,swatches:Swatches,length:Length,slider:Slider,upload:UploadArt,brief:Brief,proof:Proof,productInfo:ProductInfo,straps:StrapPicker,tails:TailShapes,bindings:FolsomBindings};
