import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Check,Download,RefreshCw,LockKeyhole,PackageCheck,ChevronRight} from 'lucide-react';
import {formatMoney} from '@rivet/configurator/product';
import './handoff.css';

const names={'on3p-custom-ski':'ON3P Custom Skis','ref-parsons':'Parsons Dining Table','vft-bistro-round':'Bistro Round'};
const label=s=>({needs_review:'Needs maker review',awaiting_acceptance:'Awaiting acceptance',quote_expired:'Quote expired',pending:'Ready to export',exported:'Awaiting receipt',failed:'Export needs attention',acknowledged:'Receipt recorded'}[s]||s);
const when=s=>new Date(s).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'});
const money=(n,c)=>formatMoney(n,c)+' '+c;
function accessFor(id){
  if(!id)return '';
  try{const token=new URLSearchParams(location.hash.slice(1)).get('access');if(token&&/^[a-f\d]{64}$/.test(token)){sessionStorage.setItem('maker-access:'+id,token);history.replaceState(null,'',location.pathname+location.search);return token;}return sessionStorage.getItem('maker-access:'+id)||'';}catch{return '';}
}
async function api(path,body,token){
  const response=await fetch('/api/handoff/'+path,{method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})});
  let value;try{value=await response.json();}catch{throw new Error('The local maker service is unavailable. Start the API and refresh.');}
  if(!response.ok)throw Object.assign(new Error(value.error||'Request failed.'),{status:response.status});return value;
}
function MinorInput({name,label:caption,defaultValue,required=true}){return <label>{caption}<input name={name} inputMode="decimal" required={required} pattern="[0-9]+([.][0-9]{1,2})?" defaultValue={defaultValue} placeholder="0.00"/></label>;}
function minor(value){if(!/^\d+(\.\d{1,2})?$/.test(value))throw new Error('Enter prices with up to two decimal places.');const [whole,cents='']=value.split('.');return Number(whole)*100+Number(cents.padEnd(2,'0'));}
function QuoteForm({build,quote,suggestion,onAction,busy}) {
  const request=useRef(null);
  async function submit(event){event.preventDefault();const form=new FormData(event.currentTarget);let input;try{input={unitMinor:minor(form.get('unit')),shippingMinor:minor(form.get('shipping')),taxMinor:minor(form.get('tax')),quantity:Number(form.get('quantity')),validityDays:Number(form.get('days')),itemCode:form.get('itemCode'),leadTime:form.get('leadTime'),terms:form.get('terms'),feasibilityReviewed:form.get('reviewed')==='on'};}catch(e){onAction(()=>Promise.reject(e));return;}
    const signature=JSON.stringify(input);if(request.current?.signature!==signature)request.current={signature,id:crypto.randomUUID()};
    await onAction(()=>api('builds/'+build.id+'/quote',{...input,id:request.current.id}),'Quote approved. The customer can now review and accept it.');
  }
  return <form className="hd-form" onSubmit={submit}><div className="hd-section-title"><h3>{quote?'Replace the quote':'Approve a quote'}</h3><span>{build.quote.currency}</span></div><p className="hd-muted">Review the specification, set the client’s item code and confirm the full price. A replacement needs fresh customer acceptance.</p><div className="hd-fields"><label>Client item code<input name="itemCode" required maxLength={80} defaultValue={quote?.itemCode||''} placeholder="e.g. CUSTOM-SKI-PAIR"/></label><label>Quantity<input name="quantity" type="number" min="1" max="10000" required defaultValue={quote?.quantity||1}/></label><MinorInput name="unit" label="Price per item" defaultValue={((quote?.unitMinor??suggestion?.unitMinor??0)/100).toFixed(2)}/><MinorInput name="shipping" label="Shipping for this order" defaultValue={((quote?.shippingMinor??0)/100).toFixed(2)}/><MinorInput name="tax" label="Tax for this order" defaultValue={((quote?.taxMinor??0)/100).toFixed(2)}/><label>Valid for (days)<input name="days" type="number" min="1" max="90" required defaultValue="14"/></label></div><label>Lead time<input name="leadTime" required maxLength={160} defaultValue={quote?.leadTime||''} placeholder="e.g. 6–8 weeks after production approval"/></label><label>Quote terms<textarea name="terms" required maxLength={2000} rows="3" defaultValue={quote?.terms||'Local pilot quote. No payment collected. Manufacturing remains on hold until the maker approves the production specification.'}/></label><label className="hd-check"><input name="reviewed" type="checkbox" required/> I reviewed the configuration and the complete quote, including tax and shipping.</label><button className="hd-primary" disabled={busy}>Approve quote <ArrowUpRight size={16}/></button></form>;
}
function Quote({quote}){return <div className="hd-quote"><div className="hd-section-title"><h3>Quote {quote.id.slice(0,8)}</h3><span className="hd-badge">{quote.status||'accepted'}</span></div><dl className="hd-spec"><div><dt>Item code / quantity</dt><dd>{quote.itemCode} × {quote.quantity}</dd></div><div><dt>Price per item</dt><dd>{money(quote.unitMinor,quote.currency)}</dd></div><div><dt>Shipping / tax</dt><dd>{money(quote.shippingMinor,quote.currency)} / {money(quote.taxMinor,quote.currency)}</dd></div><div><dt>Lead time</dt><dd>{quote.leadTime}</dd></div><div><dt>Valid until</dt><dd>{when(quote.expiresAt)}</dd></div></dl><p className="hd-total"><span>Order total</span><strong>{money(quote.totalMinor,quote.currency)}</strong></p><p className="hd-terms">{quote.terms}</p></div>;}
function Detail({data,customer,token,busy,onAction}) {
  const {build,quotes,order,delivery,events,quoteSuggestion}=data,quote=order?.quote||quotes[0],approved=quote&&['approved','accepted',undefined].includes(quote.status);
  const [confirmed,setConfirmed]=useState(false),[copied,setCopied]=useState(false);
  useEffect(()=>{setConfirmed(false);},[quote?.id]);
  const steps=[['Build saved',true],['Maker approved',approved],['Quote accepted',!!order],['Files ready',['exported','acknowledged'].includes(delivery?.status)],['Receipt recorded',delivery?.status==='acknowledged']];
  return <article className="hd-detail"><div className="hd-detail-head"><div><p className="hd-eyebrow">BUILD {build.id.slice(0,8)} · REVISION {build.revision}</p><h2>{names[build.productId]||build.productId}</h2><p className="hd-muted">Saved {when(build.createdAt)}{build.reference?' · '+build.reference:''}</p></div><button className="hd-quiet" onClick={()=>window.print()}>Print record</button></div><ol className="hd-progress">{steps.map(([name,done],i)=><li key={name} className={done?'done':''}><span>{done?<Check size={13}/>:i+1}</span>{name}</li>)}</ol><div className="hd-held"><LockKeyhole size={17}/><div><strong>Production is on hold</strong><p>This pilot records choices and commercial approval. The maker still needs to supply manufacturing materials, quantities and production steps.</p></div></div><details className="hd-specification" open><summary>Exact saved specification</summary><dl className="hd-spec">{build.specification.map((s,i)=><div key={i}><dt>{s.label}</dt><dd>{s.value}</dd></div>)}</dl><p className="hd-muted">Product version {build.productVersion} · Release {build.releaseId.slice(0,12)}<br/>Edits create a new build revision; this saved specification stays unchanged.</p></details>
    {quote&&<Quote quote={quote}/>}
    {customer&&!order&&(!quote||quote.status!=='approved')&&<div className="hd-callout"><h3>Waiting for maker review</h3><p>Your exact choices are saved. The maker will review the build and provide a quote here. Refresh to check for an update.</p></div>}
    {customer&&!order&&quote?.status==='approved'&&<form className="hd-accept" onSubmit={e=>{e.preventDefault();onAction(()=>api('builds/'+build.id+'/accept',{quoteId:quote.id,totalMinor:quote.totalMinor,currency:quote.currency,confirmed:true},token),'Quote accepted. Your pilot order is ready for the maker to export.');}}><label className="hd-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} required/> I agree to this quote and its terms. I understand this is a local pilot and no payment is collected.</label><button className="hd-primary" disabled={busy||!confirmed||quote.expiresAt<=new Date().toISOString()}>Accept pilot quote · {money(quote.totalMinor,quote.currency)}</button>{quote.expiresAt<=new Date().toISOString()&&<p role="status">This quote expired. Ask the maker for a replacement.</p>}</form>}
    {!customer&&!order&&<>{quoteSuggestion?.error?<p className="hd-error" role="alert">{quoteSuggestion.error} <a href="/manage">Manage product rules</a></p>:<><p className="hd-muted">Quote default: {quoteSuggestion?.unitMinor==null?'Maker pricing required':money(quoteSuggestion.unitMinor,build.quote.currency)}{quoteSuggestion?.priceList?' · price list v'+quoteSuggestion.priceList.version:''}. <a href={'/manage?section=price-lists&id='+build.productId}>Manage price list</a></p><QuoteForm key={build.id+':'+(quote?.id||'new')+':'+quoteSuggestion?.priceList?.version} build={build} quote={quote} suggestion={quoteSuggestion} busy={busy} onAction={onAction}/></>}{quote?.status==='approved'&&<button className="hd-quiet" disabled={busy} onClick={()=>onAction(()=>api('builds/'+build.id+'/withdraw',{quoteId:quote.id}),'Quote withdrawn.')}>Withdraw this quote</button>}</>}
    {order&&<section className="hd-export"><div className="hd-section-title"><h3><PackageCheck size={20}/> Order {order.id.slice(0,8)}</h3><span className="hd-badge">{label(delivery.status)}</span></div><p className="hd-muted">Accepted {when(order.createdAt)} · No payment collected</p>{delivery.error&&<p role="alert" className="hd-error">{delivery.error}</p>}{!customer&&<>{['pending','failed'].includes(delivery.status)&&<button className="hd-primary" disabled={busy} onClick={()=>onAction(()=>api('builds/'+build.id+'/export',{}),'Export preparation complete. Check the delivery status below.')}>{delivery.status==='failed'?'Retry export':'Prepare order exports'} <Download size={16}/></button>}{['exported','acknowledged'].includes(delivery.status)&&<><div className="hd-downloads">{['csv','json'].map(format=><a className="hd-button" key={format} href={'/api/handoff/builds/'+build.id+'/file?format='+format}><Download size={16}/> Download {format.toUpperCase()}</a>)}</div><p className="hd-muted">CSV: one sales line for a spreadsheet or import. JSON: complete build, quote and approval record. Downloading does not confirm receipt.</p>{delivery.status!=='acknowledged'&&<form className="hd-form" onSubmit={e=>{e.preventDefault();const receipt=new FormData(e.currentTarget).get('receipt');onAction(()=>api('builds/'+build.id+'/acknowledge',{receipt}),'Destination receipt recorded.');}}><label>Destination receipt / external order reference<input name="receipt" required maxLength={240} placeholder="e.g. Production sheet, row 24 / ERP SO-1042"/></label><button className="hd-primary" disabled={busy}>Record destination receipt <Check size={16}/></button></form>}</>}</>}{delivery.receipt&&<p className="hd-receipt"><Check size={16}/> {delivery.receipt} · {when(delivery.acknowledgedAt)}</p>}</section>}
    {customer&&token&&<div className="hd-share"><button className="hd-quiet" onClick={()=>onAction(async()=>{await navigator.clipboard.writeText(location.origin+'/handoff/build/'+build.id+'#access='+token);setCopied(true);})}>{copied?'Private review link copied':'Copy private review link'}</button><p className="hd-muted">Keep this link to return to the build and accept its quote. Anyone with the link can access this pilot build.</p></div>}
    <details className="hd-history"><summary>Activity history · {events.length}</summary><ol>{events.map(e=><li key={e.seq}><strong>{e.kind.replaceAll('.',' · ').replaceAll('_',' ')}</strong><time>{when(e.at)}</time></li>)}</ol></details>
  </article>;
}
export default function HandoffDesk(){
  const customerId=location.pathname.match(/^\/handoff\/build\/([a-f\d-]{36})$/i)?.[1],customer=!!customerId;
  const [token]=useState(()=>accessFor(customerId));
  const [session,setSession]=useState(null),[rows,setRows]=useState([]),[selected,setSelected]=useState(customerId||new URLSearchParams(location.search).get('build')||''),[data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[filter,setFilter]=useState('all');
  const latestSelection=useRef(selected);latestSelection.current=selected;
  async function refresh(id=selected){const state=await api('session');setSession(state);if(!customer&&state.operator)setRows(await api('builds'));if(id&&(customer||state.operator)){const value=await api('builds/'+id,undefined,token);if(latestSelection.current===id)setData(value);}}
  useEffect(()=>{document.title=customer?'Your saved build · Maker Studio':'Handoff desk · Maker Studio';refresh().catch(e=>setError(e.message));},[]);
  async function action(fn,message=''){if(busy)return;setBusy(true);setError('');setNotice('');try{await fn();await refresh();setNotice(message);}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function select(id){setSelected(id);latestSelection.current=id;setData(null);setError('');history.replaceState(null,'','/handoff?build='+id);try{await refresh(id);}catch(e){setError(e.message);}}
  const visible=rows.filter(r=>filter==='all'||(filter==='review'?['needs_review','quote_expired','awaiting_acceptance'].includes(r.status):filter==='received'?r.status==='acknowledged':['pending','failed','exported'].includes(r.status)));
  return <div className="hd-app"><header className="hd-header"><a className="hd-brand" href="/manage">Maker Studio <ArrowUpRight size={15}/></a><a className="hd-desk-link" href="/handoff">Handoff desk</a><a className="hd-desk-link" href="/manage">Management</a><div><span className="hd-pilot">Local pilot</span>{session?.operator&&<button onClick={()=>action(async()=>{await api('logout',{});setData(null);setRows([]);},'Signed out.')}>Sign out</button>}</div></header><main className={'hd-main '+(customer?'hd-customer':'')}><div className="hd-intro"><p className="hd-eyebrow">{customer?'YOUR SAVED BUILD':'MAKER OPERATIONS'}</p><h1>{customer?'The next step, together.':'From chosen to received.'}</h1><p>{customer?'Review the maker’s quote, accept it and follow the handoff.':'Review the build. Confirm the quote. Keep the handoff accounted for.'}</p><p className="hd-local-note">This workspace is a local demonstration. It does not contact manufacturers, collect payments or release production.</p></div><div className="hd-toolbar"><span>{customer?'Your private build record':session?.operator?rows.length+' saved build'+(rows.length===1?'':'s'):'Private maker workspace'}</span><button disabled={busy} onClick={()=>action(()=>Promise.resolve())}><RefreshCw size={14}/> Refresh</button></div>{error&&<div role="alert" className="hd-error">{error}</div>}{notice&&<div role="status" className="hd-notice">{notice}</div>}{!session&&!error&&<p role="status">Opening the maker desk…</p>}
    {!customer&&session&&!session.operator&&<form className="hd-login hd-form" onSubmit={e=>{e.preventDefault();const password=new FormData(e.currentTarget).get('password');action(()=>api(session.setupRequired?'setup':'login',{password}),'Maker desk ready.');}}><LockKeyhole size={27}/><h2>{session.setupRequired?'Set up your maker desk':'Welcome back'}</h2><p>{session.setupRequired?'Create a password for the maker review and export controls on this computer.':'Sign in to review builds and manage their handoffs.'}</p><label>Maker password<input name="password" type="password" required minLength={session.setupRequired?12:1} maxLength={200} autoComplete={session.setupRequired?'new-password':'current-password'}/></label><p className="hd-muted">{session.setupRequired?'At least 12 characters. Customer review links have their own separate access.':'Your maker session lasts eight hours.'}</p><button className="hd-primary" disabled={busy}>{session.setupRequired?'Create maker account':'Sign in'}</button></form>}
    {!customer&&session?.operator&&<><div className="hd-metrics">{[['To review',rows.filter(r=>['needs_review','quote_expired'].includes(r.status)).length],['In handoff',rows.filter(r=>['pending','exported','failed'].includes(r.status)).length],['Received',rows.filter(r=>r.status==='acknowledged').length]].map(([title,value])=><div key={title}><span>{title}</span><strong>{value}</strong></div>)}</div><div className="hd-workspace"><aside className="hd-inbox"><label className="hd-filter">Show builds<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All builds</option><option value="review">Review &amp; acceptance</option><option value="handoff">Handoff</option><option value="received">Received</option></select></label>{visible.map(row=><button className={'hd-row '+(selected===row.id?'selected':'')} key={row.id} onClick={()=>select(row.id)}><span className="hd-row-id">{row.id.slice(0,8)} · REV {row.revision}<ChevronRight size={15}/></span><strong>{names[row.productId]||row.productId}</strong><span>{row.totalMinor===null?'Quote required':money(row.totalMinor,row.currency)}</span><span className={'hd-status '+row.status}>{label(row.status)}</span></button>)}{!visible.length&&<p className="hd-empty">No builds in this view.</p>}<a className="hd-new" href="http://127.0.0.1:5178/">Configure ON3P skis <ArrowUpRight size={14}/></a><a className="hd-new" href="/products/vft-bistro-round">Configure a table <ArrowUpRight size={14}/></a></aside>{data?<Detail key={data.build.id} data={data} customer={false} busy={busy} onAction={action}/>:<section className="hd-empty-detail"><PackageCheck size={36}/><h2>{selected?'Opening the saved record':'A clear path to handoff.'}</h2><p>{selected?'Use Refresh if the service has restarted.':'Select a build to review its exact choices, approve a quote and prepare the order exports.'}</p></section>}</div></>}
    {customer&&data&&<Detail key={data.build.id} data={data} customer token={token} busy={busy} onAction={action}/>}{customer&&<a className="hd-new" href="/handoff">Open the maker desk <ArrowUpRight size={14}/></a>}
    </main><footer className="hd-footer">Maker Studio / Handoff foundation <span>Manual file delivery · Production approval required</span></footer></div>;
}
